### ISSUE TITLE
Running "pasta analyse succ" in mbox mode doesnt show appropriate error message

### ISSUE THREAD

**Issue by rsarky** [lfd/PaStA#44]
Analysing successive patches should only be possible in patch stack mode.
Currently, if I run `patch analyse succ` with Linux as my selected configuration this is the output:
```
2020-03-18 00:28:48,876 PaStA           INFO     Cmdline: ./pasta analyse succ
2020-03-18 00:28:48,876 pypasta.Config  INFO     Active configuration: linux
2020-03-18 00:28:48,931 Repository.Mbox INFO     Loading mailbox subsystem
2020-03-18 00:28:52,341 Repository.Mbox INFO       ↪ loaded invalid mail index: found 3830608 invalid mails
2020-03-18 00:28:52,341 Repository.Mbox INFO     Loading public inboxes
2020-03-18 00:28:55,423 Repository.Mbox INFO       ↪ loaded mail index for alsa-devel@alsa-project.org (shard 0): found 207512 mails
2020-03-18 00:29:01,327 n.pasta_analyse INFO     Regarding mails in time window 2010-01-01--2010-03-01
2020-03-18 00:29:01,327 tory.Repository INFO     Loading mbox commit cache
2020-03-18 00:29:01,329 tory.Repository INFO       ↪ Warning, commit cache file /home/rohit/Projects/PaStA/resources/linux/resources/commit_cache_mbox.pkl not found!
Traceback (most recent call last):
  File "./pasta", line 178, in <module>
    ret = main(deepcopy(sys.argv))
  File "./pasta", line 143, in main
    return analyse(config, sub, argv)
  File "/home/rohit/Projects/PaStA/bin/pasta_analyse.py", line 217, in analyse
    victims = config.psd.commits_on_stacks
  File "/home/rohit/Projects/PaStA/pypasta/Config.py", line 338, in psd
    return self.patch_stack_definition
AttributeError: 'Config' object has no attribute 'patch_stack_definition'
```
Although it should throw an error saying `Analysis mode succ is not available in mailbox mode!` 

This error is due to a bug in the argument parsing sequence in `pasta_analyse.py`

**Comment by rralf** [comment]
Yep yep yep, as mentioned in the other thread, you're totally right.

But look on the next branch, I already addressed this issue: a25ee746a4075bca255678424beff6dafee0750f

**Comment by rsarky** [comment]
Ah. Should probably have checkout the next branch before submitting the fix
My bad

**Comment by rsarky** [comment]
Although I still feel the if else ladder could be refactored to read a little better. Could you take a look at the PR referring this issue

**Comment by rralf** [comment]
Go ahead! I guess we can close this issue for the moment, right? (I'm loosing overview ;-) )

**Comment by rsarky** [comment]
Haha yes. Closing
